### ISSUE TITLE
[Enhancement suggestions] - Conditionnal display of extra user fields on signup form

### ISSUE THREAD

**Issue by Quentinchampenois** [PopulateTools/decidim-module-extra_user_fields#8]
Hello, 

#### Description 

We started to work on a [very similar module](https://github.com/Quentinchampenois/decidim-module-modulable_registration) where administrators can choose between pre-defined extra user fields in signup form. 

There is a backoffice section where admin can enable / disable the extra user fields. Also, each extra field can be enabled / disabled. 

As discussed with [@simonaszilinskas](https://github.com/simonaszilinskas), we would be happy to contribute by implementing this feature in your module if it interests you.

#### Features

- [ ] Add a Backoffice section under `Settings > Extra user fields` 
  - [ ] Allow to activate / deactivate extra user fields module in signup form
  - [ ] Choose explicitly which fields are activated
- [ ] In signup form, display conditionnaly activated fields
- [ ] Activate form validations only for activated extra fields
- [ ] Display conditionnaly enabled extra fields in account form (Need discussion)
- [ ] Display conditionnaly enabled extra fields in user exports (Need discussion)

#### Related

Maybe add light documentation for creating a new extra field (cf: #2)

#### Screenshots

This is an example of Backoffice UI 

<img width="500" alt="bo_enabled" src="https://user-images.githubusercontent.com/26109239/197520914-ec5e3be9-c82a-4e81-930f-acdd96334379.png">
<img width="500" alt="bo_disabled" src="https://user-images.githubusercontent.com/26109239/197520924-2072ee07-52ec-4951-9817-5b6769174133.png">

Dedicated section in FO signup form
<img width="500" alt="signup_form" src="https://user-images.githubusercontent.com/26109239/197521081-13acdd6e-eea4-4cd0-9f60-cdf74950ef87.png">

Let me know your questions, suggestions, feedback etc

Thanks !

**Comment by furilo** [comment]
Hi @Quentinchampenois - thanks for the interest. We totally welcome the improvements you talk about ;)

**Comment by Quentinchampenois** [comment]
Closed by #9 !
